### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [mumble-voip/mumble-www#174] opened 2022-01-19 05:40 UTC
Dear @mumble-voip team,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/mumble/news/
- https://sourceforge.net/p/mumble/_list/tickets
- https://sourceforge.net/p/mumble/bugs/
- https://sourceforge.net/p/mumble/feature-requests/
- https://sourceforge.net/p/mumble/patches/
- https://sourceforge.net/p/mumble/discussion/
- https://sourceforge.net/p/mumble/discussion/492606/
- https://sourceforge.net/p/mumble/discussion/492607/
- https://sourceforge.net/p/mumble/mailman/
- https://sourceforge.net/p/mumble/mailman/mumble-packaging/
- https://sourceforge.net/p/mumble/mailman/mumble-translations/

To remove the old not updated: http://mumble.sourceforge.net/ and use only https://www.mumble.info/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/mumble/

To disable/delete tabs, go here: https://sourceforge.net/projects/mumble/
To add a new tab, go here: https://sourceforge.net/projects/mumble/
To change informations, go here: https://sourceforge.net/p/mumble/admin/overview
To export, go here: https://sourceforge.net/p/mumble/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/mumble/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/mumble/admin/overview
- A new tab, go here: https://sourceforge.net/projects/mumble/

Remove the false Twitter and Facebook links: https://sourceforge.net/p/mumble/admin/overview

The support page will be updated: https://sourceforge.net/projects/mumble/support

Thanks in advance.

**Comment by Krzmbrzl** [comment] 2022-01-19 06:46
Duplicate of https://github.com/mumble-voip/mumble/issues/5471

**Closed** 2022-01-19 06:46 UTC
